[2024-09-11T05:24:53.160+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_analysis_by_dbt.transform_analaysis scheduled__2024-06-01T15:00:00+00:00 [queued]>
[2024-09-11T05:24:53.170+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: transform_analysis_by_dbt.transform_analaysis scheduled__2024-06-01T15:00:00+00:00 [queued]>
[2024-09-11T05:24:53.170+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-09-11T05:24:53.171+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-09-11T05:24:53.171+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-09-11T05:24:53.181+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): transform_analaysis> on 2024-06-01 15:00:00+00:00
[2024-09-11T05:24:53.185+0000] {standard_task_runner.py:55} INFO - Started process 6089 to run task
[2024-09-11T05:24:53.187+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'transform_analysis_by_dbt', 'transform_analaysis', 'scheduled__2024-06-01T15:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dbt_transform_analysis.py', '--cfg-path', '/tmp/tmp8kq1c_a6']
[2024-09-11T05:24:53.187+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask transform_analaysis
[2024-09-11T05:24:53.237+0000] {task_command.py:388} INFO - Running <TaskInstance: transform_analysis_by_dbt.transform_analaysis scheduled__2024-06-01T15:00:00+00:00 [running]> on host 392ef5210b0f
[2024-09-11T05:24:53.355+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=hyoungwon
AIRFLOW_CTX_DAG_ID=transform_analysis_by_dbt
AIRFLOW_CTX_TASK_ID=transform_analaysis
AIRFLOW_CTX_EXECUTION_DATE=2024-06-01T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-01T15:00:00+00:00
[2024-09-11T05:24:53.358+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-09-11T05:24:53.359+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir .']
[2024-09-11T05:24:53.373+0000] {subprocess.py:86} INFO - Output:
[2024-09-11T05:24:55.172+0000] {subprocess.py:93} INFO - [0m05:24:55  Running with dbt=1.8.6
[2024-09-11T05:24:55.518+0000] {subprocess.py:93} INFO - [0m05:24:55  Registered adapter: redshift=1.8.1
[2024-09-11T05:24:56.092+0000] {subprocess.py:93} INFO - [0m05:24:56  Found 9 models, 3 seeds, 486 macros
[2024-09-11T05:24:56.095+0000] {subprocess.py:93} INFO - [0m05:24:56
[2024-09-11T05:24:56.343+0000] {subprocess.py:93} INFO - [0m05:24:56
[2024-09-11T05:24:56.343+0000] {subprocess.py:93} INFO - [0m05:24:56  Finished running  in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2024-09-11T05:24:56.344+0000] {subprocess.py:93} INFO - [0m05:24:56  Encountered an error:
[2024-09-11T05:24:56.344+0000] {subprocess.py:93} INFO - Database Error
[2024-09-11T05:24:56.344+0000] {subprocess.py:93} INFO -   {'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user "wnsldjqja"', 'F': '/home/ec2-user/padb/src/pg/src/backend/libpq/auth.c', 'L': '425', 'R': 'auth_failed'}
[2024-09-11T05:24:57.810+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-11T05:24:57.818+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-11T05:24:57.820+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=transform_analysis_by_dbt, task_id=transform_analaysis, execution_date=20240601T150000, start_date=20240911T052453, end_date=20240911T052457
[2024-09-11T05:24:57.830+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 13 for task transform_analaysis (Bash command failed. The command returned a non-zero exit code 2.; 6089)
[2024-09-11T05:24:57.853+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-09-11T05:24:57.865+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
